[2024-04-01T11:53:18.285+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.fetch_pageviews manual__2024-04-01T11:52:57.251297+00:00 [queued]>
[2024-04-01T11:53:18.291+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chapter4_stocksense_bashoperator.fetch_pageviews manual__2024-04-01T11:52:57.251297+00:00 [queued]>
[2024-04-01T11:53:18.291+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-01T11:53:18.307+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): fetch_pageviews> on 2024-04-01 11:52:57.251297+00:00
[2024-04-01T11:53:18.311+0000] {standard_task_runner.py:60} INFO - Started process 203 to run task
[2024-04-01T11:53:18.313+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'chapter4_stocksense_bashoperator', 'fetch_pageviews', 'manual__2024-04-01T11:52:57.251297+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/pages_dag.py', '--cfg-path', '/tmp/tmpcxn_qfyn']
[2024-04-01T11:53:18.324+0000] {standard_task_runner.py:88} INFO - Job 140: Subtask fetch_pageviews
[2024-04-01T11:53:18.375+0000] {task_command.py:423} INFO - Running <TaskInstance: chapter4_stocksense_bashoperator.fetch_pageviews manual__2024-04-01T11:52:57.251297+00:00 [running]> on host d7148197e99c
[2024-04-01T11:53:18.430+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chapter4_stocksense_bashoperator' AIRFLOW_CTX_TASK_ID='fetch_pageviews' AIRFLOW_CTX_EXECUTION_DATE='2024-04-01T11:52:57.251297+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-01T11:52:57.251297+00:00'
[2024-04-01T11:53:33.441+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pages_dag.py", line 60, in _fetch_pageviews
    "INSERT INTO pageview_counts VALUES ("
NameError: name 'execution_date' is not defined
[2024-04-01T11:53:33.448+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=chapter4_stocksense_bashoperator, task_id=fetch_pageviews, execution_date=20240401T115257, start_date=20240401T115318, end_date=20240401T115333
[2024-04-01T11:53:33.456+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 140 for task fetch_pageviews (name 'execution_date' is not defined; 203)
[2024-04-01T11:53:33.465+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-01T11:53:33.471+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/models/baseoperator.py:1201: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-04-01T11:53:33.480+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
